name: MeT-Music
version: 1.4
main: top.met6.metmusic.MetMusicPlugin
api-version: 1.16
commands:
  mmusic:
    description: MeT-Music 点歌插件命令
    usage: /<command> [帮助|playmid <mid>|...]
    aliases: [music]